/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMFoundation.h"

@class IMServiceImpl, IMPeople, IMPerson, IMHandle, IMRemoteObject, IMLocalObject, IMDaemonListener;

struct _FZChatRoomValidity {
    int _field1;
    unsigned short _field2;
};

/*
 * File: IMCore_thin
 * Arch: Intel 80x86 (i386)
 *       Current version: 701.0.0, Compatibility version: 1.0.0
 */

@protocol DirectlyObservableObjectObserver
- (void)objectDidPostDirectNotification:(id)fp8;
@end

@protocol FZDaemon <NSObject>
- (oneway void)autoLoginActiveAccountsIfNecessary;
- (oneway void)loginAllAccounts;
- (oneway void)logoutAllAccounts;
- (oneway void)terminate;
- (oneway void)changeMyStatus:(id)fp8 forAccount:(id)fp12;
- (oneway void)setValue:(id)fp8 ofPersistentProperty:(id)fp12;
- (oneway void)setVCCapabilities:(unsigned long long)fp8;
- (oneway void)requestCurrentAVChatInfoForListenerID:(id)fp8 responseID:(id)fp12;
- (oneway void)requestAudioReflector:(BOOL)fp8 forListenerID:(id)fp12 responseID:(id)fp16;
- (oneway void)requestVideoStillForPerson:(id)fp8 forListenerID:(id)fp12 responseID:(id)fp16;
- (oneway void)provideCurrentAVChatInfo:(id)fp8 result:(unsigned int)fp12 transactionID:(unsigned int)fp16;
- (oneway void)provideVideoStill:(id)fp8 forPerson:(id)fp12 result:(unsigned int)fp16 transactionID:(unsigned int)fp20;
- (oneway void)setAVManagerClient:(id)fp8 URLToShare:(id)fp12;
- (oneway void)activateAccounts:(id)fp8;
- (oneway void)deactivateAccounts:(id)fp8;
- (oneway void)addAccount:(id)fp8 defaults:(id)fp12 service:(id)fp16;
- (oneway void)removeAccount:(id)fp8;
- (oneway void)writeAccount:(id)fp8 defaults:(id)fp12;
- (oneway void)holdBuddyUpdatesForAccount:(id)fp8;
- (oneway void)resumeBuddyUpdatesForAccount:(id)fp8;
- (oneway void)autoLoginWithAccount:(id)fp8;
- (oneway void)loginWithAccount:(id)fp8;
- (oneway void)logoutOfAccount:(id)fp8;
- (oneway void)sessionCertificatesChangedForAccount:(id)fp8;
- (oneway void)enableSecureIM:(BOOL)fp8 forAccount:(id)fp12;
- (oneway void)disableCertificatesForPerson:(id)fp8 forAccount:(id)fp12;
- (oneway void)requestBuddyPicturesAndPropertiesForAccount:(id)fp8;
- (oneway void)requestProperty:(id)fp8 ofPerson:(id)fp12 forAccount:(id)fp16;
- (oneway void)setValue:(id)fp8 ofProperty:(id)fp12 ofPerson:(id)fp16 forAccount:(id)fp20;
- (oneway void)requestGroupsForAccount:(id)fp8;
- (oneway void)changeGroups:(id)fp8 forAccount:(id)fp12;
- (oneway void)changeGroup:(id)fp8 changes:(id)fp12 forAccount:(id)fp16;
- (oneway void)renameGroup:(id)fp8 to:(id)fp12 forAccount:(id)fp16;
- (oneway void)createChatForIMsWith:(id)fp8 isDirect:(BOOL)fp12 forAccount:(id)fp16;
- (oneway void)createChatWith:(id)fp8 invitation:(id)fp12 named:(id)fp16 forAccount:(id)fp20;
- (oneway void)goToChatNamed:(id)fp8 forAccount:(id)fp12;
- (oneway void)invitePerson:(id)fp8 toChat:(id)fp12 withMessage:(id)fp16;
- (oneway void)respond:(BOOL)fp8 toInvitationToChat:(id)fp12;
- (oneway void)sendMessage:(id)fp8 toChat:(id)fp12;
- (oneway void)leaveChat:(id)fp8;
- (oneway void)setPerson:(id)fp8 isIgnored:(BOOL)fp12 inChat:(id)fp16;
- (oneway void)sendStandaloneFileTransfer:(id)fp8;
- (oneway void)fileTransfer:(id)fp8 createdWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 acceptedWithPath:(id)fp12 autoRename:(BOOL)fp16 overwrite:(BOOL)fp20;
- (oneway void)fileTransferStopped:(id)fp8;
- (oneway void)fileTransferRemoved:(id)fp8;
- (oneway void)requestVCWithPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)cancelVCRequestWithPerson:(id)fp8 forAccount:(id)fp12;
- (oneway void)respondToVCInvitationWithPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendCounterProposalToPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendVCUpdate:(id)fp8 toPerson:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendAVMessageToPerson:(id)fp8 sessionID:(unsigned int)fp12 type:(unsigned int)fp16 userInfo:(id)fp20 forAccount:(id)fp24;
- (oneway void)setBlockList:(id)fp8 forAccount:(id)fp12;
- (oneway void)setAllowList:(id)fp8 forAccount:(id)fp12;
- (oneway void)setBlockingMode:(unsigned int)fp8 forAccount:(id)fp12;
- (oneway void)setBlockIdleStatus:(BOOL)fp8 forAccount:(id)fp12;
- (oneway void)acceptSubscriptionRequest:(BOOL)fp8 from:(id)fp12 forAccount:(id)fp16;
- (oneway void)requestSubscriptionTo:(id)fp8 forAccount:(id)fp12;
- (oneway void)startWatchingBuddy:(id)fp8 forAccount:(id)fp12;
- (oneway void)stopWatchingBuddy:(id)fp8 forAccount:(id)fp12;
- (oneway void)addListener:(id)fp8 withListenerID:(id)fp12 capabilities:(unsigned int)fp16;
@end

@protocol FZDaemonListener <NSObject>
- (oneway void)services:(id)fp8 persistentProperties:(id)fp12;
- (oneway void)service:(id)fp8 properties:(id)fp12 defaults:(id)fp16 defaultAccountSettings:(id)fp20 allAccounts:(id)fp24 activeAccounts:(id)fp28;
- (oneway void)account:(id)fp8 status:(id)fp12 capabilities:(unsigned long long)fp16 serviceLoginStatus:(unsigned int)fp24 loginStatusMessage:(id)fp28;
- (oneway void)setupComplete;
- (oneway void)vcCapabilitiesChanged:(unsigned long long)fp8;
- (oneway void)defaultsChanged:(id)fp8 forService:(id)fp12;
- (oneway void)activeAccountsChanged:(id)fp8 forService:(id)fp12;
- (oneway void)account:(id)fp8 loginStatusChanged:(unsigned int)fp12 message:(id)fp16 reason:(unsigned int)fp20 properties:(id)fp24;
- (oneway void)account:(id)fp8 defaultsChanged:(id)fp12;
- (oneway void)account:(id)fp8 capabilitiesChanged:(unsigned long long)fp12;
- (oneway void)accountAdded:(id)fp8 defaults:(id)fp12 service:(id)fp16;
- (oneway void)accountRemoved:(id)fp8;
- (oneway void)account:(id)fp8 buddyPropertiesChanged:(id)fp12;
- (oneway void)account:(id)fp8 blockListChanged:(id)fp12;
- (oneway void)account:(id)fp8 allowListChanged:(id)fp12;
- (oneway void)account:(id)fp8 blockingModeChanged:(unsigned int)fp12;
- (oneway void)account:(id)fp8 blockIdleStatusChanged:(BOOL)fp12;
- (oneway void)account:(id)fp8 buddyPictureChanged:(id)fp12 imageData:(id)fp16 imageHash:(id)fp20;
- (oneway void)account:(id)fp8 groupsChanged:(id)fp12 error:(id)fp16;
- (oneway void)account:(id)fp8 buddyProperties:(id)fp12 buddyPictures:(id)fp16;
- (oneway void)account:(id)fp8 handleSubscriptionRequestFrom:(id)fp12;
- (oneway void)invitedToChat:(id)fp8 isChatRoom:(BOOL)fp12 invitation:(id)fp16;
- (oneway void)account:(id)fp8 directIMRequestFrom:(id)fp12 invitation:(id)fp16;
- (oneway void)chat:(id)fp8 messageReceived:(id)fp12;
- (oneway void)chat:(id)fp8 showError:(id)fp12;
- (oneway void)chat:(id)fp8 statusChanged:(int)fp12;
- (oneway void)chat:(id)fp8 member:(id)fp12 statusChanged:(int)fp16;
- (oneway void)standaloneFileTransferRegistered:(id)fp8;
- (oneway void)allFileTransfers:(id)fp8;
- (oneway void)fileTransfer:(id)fp8 createdWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithCurrentBytes:(unsigned long long)fp12 totalBytes:(unsigned long long)fp20 averageTransferRate:(unsigned long long)fp28;
- (oneway void)account:(id)fp8 invitedToVC:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 responseToVCRequest:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 cancelVCInviteFrom:(id)fp12;
- (oneway void)account:(id)fp8 counterProposalFrom:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 updateVCFrom:(id)fp12 data:(id)fp16;
- (oneway void)account:(id)fp8 handleAVMessage:(id)fp12 sessionID:(unsigned int)fp16 type:(unsigned int)fp20 userInfo:(id)fp24;
- (oneway void)showInvalidCertNotificationForAccount:(id)fp8;
- (oneway void)showForgotPasswordNotificationForAccount:(id)fp8;
- (oneway void)account:(id)fp8 statusChanged:(id)fp12;
- (oneway void)daemonPersistentProperty:(id)fp8 changedTo:(id)fp12;
- (oneway void)account:(id)fp8 postedError:(id)fp12;
- (oneway void)currentAVChatInfoRequestedWithTransactionID:(unsigned int)fp8;
- (oneway void)audioReflectorRequested:(BOOL)fp8 transactionID:(unsigned int)fp12;
- (oneway void)videoStillForPersonRequested:(id)fp8 withTransactionID:(unsigned int)fp12;
- (oneway void)currentAVChatInfoProvided:(id)fp8 result:(unsigned int)fp12 responseID:(id)fp16;
- (oneway void)videoStill:(id)fp8 providedForPerson:(id)fp12 result:(unsigned int)fp16 responseID:(id)fp20;
- (oneway void)setAVManagerRequested:(BOOL)fp8 URLToShare:(id)fp12;
@end

@protocol NetworkChangeNotificationListener
- (void)systemNetworkDidChange;
- (void)systemWillSleep;
- (void)systemDidWake;
@end

@interface IMAccount : NSObject <NetworkChangeNotificationListener>
{
    IMServiceImpl *_service;
    IMPeople *_buddyList;
    NSMutableDictionary *_imHandles;
    NSMutableDictionary *_inlineTransfers;
    IMHandle *_loginIMHandle;
    NSString *_loginID;
    NSString *_uniqueID;
    NSMutableDictionary *_data;
    NSMutableDictionary *_accountPreferences;
    int _loginStatus;
    BOOL _isActive;
    NSArray *_groups;
    BOOL _justLoggedIn;
    BOOL _asleep;
    BOOL _useMeCardName;
    unsigned long long _capabilities;
    int _cachedBlockingMode;
    NSArray *_cachedAllowList;
    NSArray *_cachedBlockList;
    BOOL _blockIdleStatus;
    BOOL _blockOtherAddresses;
    BOOL _allowsVCRelay;
    BOOL _syncedBuddies;
    BOOL _syncedWithRemoteBuddyList;
    BOOL _hasReceivedSync;
    NSMutableDictionary *_sortOrders;
    NSDictionary *_members;
    int _numHolding;
    int _coalesceCount;
    NSMutableDictionary *_coalescedChanges;
    NSArray *_targetGroupState;
    NSArray *_lastReceivedGroupState;
    NSImage *_smallImage;
    NSImage *_accountImage;
    BOOL _needToCheckForWatchedIMHandles;
    BOOL _iconChecked;
    NSDictionary *_subtypeInfo;
    NSMutableDictionary *_currentAccountStatus;
    unsigned int _myStatus;
    NSString *_myStatusMessage;
    NSDictionary *_myNowPlaying;
    NSDate *_myIdleSince;
    NSData *_myPictureData;
    NSAttributedString *_myProfile;
}

+ (id)passwordForAccount:(id)fp8 forServiceName:(id)fp12;
+ (void)setPassword:(id)fp8 forAccount:(id)fp12 forServiceName:(id)fp16;
+ (void)removePasswordForAccount:(id)fp8 forServiceName:(id)fp12;
+ (id)nameOfLoginStatus:(int)fp8;
+ (id)arrayOfAllIMHandles;
+ (id)allBuddyListIMHandles;
- (void)dealloc;
- (void)clearServiceCaches;
- (id)initWithUniqueID:(id)fp8 service:(id)fp12;
- (unsigned int)status;
- (id)login;
- (id)service;
- (void)_loginWithAutoLogin:(BOOL)fp8;
- (void)autoLoginAccount;
- (void)loginAccount;
- (void)logoutAccount;
- (void)loginStatusChanged:(unsigned int)fp8 message:(id)fp12 reason:(unsigned int)fp16 properties:(id)fp20;
- (void)setLogin:(id)fp8;
- (void)_updateMyStatus:(unsigned int)fp8 message:(id)fp12;
- (void)setCurrentAccountStatus:(id)fp8;
- (id)myNowPlayingString;
- (id)currentAccountStatus;
- (id)myProfile;
- (unsigned int)myStatus;
- (id)myStatusMessage;
- (id)myPictureData;
- (id)myIdleSince;
- (id)uniqueID;
- (void)setUniqueID:(id)fp8;
- (id)shortName;
- (id)internalName;
- (id)name;
- (id)serviceName;
- (id)canonicalFormOfID:(id)fp8;
- (BOOL)equalID:(id)fp8 andID:(id)fp12;
- (void)writeSettings;
- (void)resetToDefaults;
- (BOOL)emailAddressIsID:(id)fp8;
- (unsigned long long)capabilities;
- (BOOL)hasCapability:(unsigned long long)fp8;
- (void)updateCapabilities:(unsigned long long)fp8;
- (BOOL)handlesChatInvites;
- (BOOL)canBeSecure;
- (id)password;
- (void)setPassword:(id)fp8;
- (void)removePassword;
- (BOOL)isInvisible;
- (void)setInvisible:(BOOL)fp8;
- (id)description;
- (void)setDescription:(id)fp8;
- (BOOL)hasCustomDescription;
- (BOOL)autoLogin;
- (void)setAutoLogin:(BOOL)fp8;
- (BOOL)useSSL;
- (id)_serverWithSSL:(BOOL)fp8;
- (id)server;
- (int)port;
- (BOOL)goIdle;
- (void)setGoIdle:(BOOL)fp8;
- (BOOL)allowsVCRelay;
- (void)setAllowsVCRelay:(BOOL)fp8;
- (BOOL)canActivate;
- (BOOL)validLogin;
- (BOOL)validPort;
- (BOOL)validServer;
- (BOOL)isManaged;
- (int)invalidSettings;
- (void)enableSecureIM:(BOOL)fp8;
- (void)disableCertificatesForIMHandle:(id)fp8;
- (void)setSecureImEnabled:(BOOL)fp8;
- (BOOL)secureImEnabled;
- (int)accountLoginStatus;
- (void)requestProperty:(id)fp8 ofIMHandle:(id)fp12;
- (void)setValue:(id)fp8 ofExtraProperty:(id)fp12 ofIMHandle:(id)fp16;
- (void)loadFromDictionary:(id)fp8;
- (id)dictionary;
- (id)addressBookProperty;
- (id)emailDomains;
- (void)setCachedAllowList:(id)fp8;
- (void)setCachedBlockList:(id)fp8;
- (void)setCachedBlockingMode:(unsigned int)fp8;
- (void)setCachedBlockIdleStatus:(BOOL)fp8;
- (void)blockMessages:(BOOL)fp8 fromID:(id)fp12;
- (void)setBlockList:(id)fp8;
- (id)blockList;
- (void)setAllowList:(id)fp8;
- (id)allowList;
- (void)setBlockingMode:(unsigned int)fp8;
- (unsigned int)blockingMode;
- (BOOL)blockIdleStatus;
- (void)setBlockIdleStatus:(BOOL)fp8;
- (BOOL)blockOtherAddresses;
- (void)setBlockOtherAddresses:(BOOL)fp8;
- (void)clearTargetState;
- (BOOL)isAwaitingTargetGroupState;
- (BOOL)hasTargetGroupStateBeenMet;
- (void)targetGroupStateTimeout;
- (void)setWaitForTargetState;
- (void)updateWithTargetGroups;
- (void)setTargetGroupsState:(id)fp8;
- (void)_applyChangesToTemporaryCache:(id)fp8;
- (void)beginChanges;
- (void)hookupToDaemon;
- (void)requestGroups;
- (BOOL)hasSyncedWithRemoteBuddies;
- (void)syncWithRemoteBuddies;
- (void)changeBuddyList:(id)fp8 add:(BOOL)fp12 groups:(id)fp16 atLocation:(int)fp20;
- (void)renameGroup:(id)fp8 to:(id)fp12;
- (void)reorderGroup:(id)fp8 order:(id)fp12;
- (void)reorderGroups:(id)fp8;
- (id)propertiesForGroup:(id)fp8;
- (id)groupMembers:(id)fp8;
- (id)groupList;
- (id)memberGroups:(id)fp8;
- (void)endChanges;
- (BOOL)makingChanges;
- (void)holdBuddyUpdates;
- (void)_resumeBuddyUpdatesNow;
- (void)resumeBuddyUpdates;
- (void)buddyPropertiesChanged:(id)fp8;
- (void)buddyPictureChanged:(id)fp8 imageData:(id)fp12 imageHash:(id)fp16;
- (void)setBuddyProperties:(id)fp8 buddyPictures:(id)fp12;
- (void)_serviceDidConnect:(id)fp8;
- (void)_serviceDidReconnect:(id)fp8;
- (void)_serviceDidDisconnect:(id)fp8;
- (void)accountDidBecomeActive;
- (void)accountDidDeactivate;
- (void)_notJustLoggedIn;
- (id)accountLoginStatusMessage;
- (BOOL)connecting;
- (BOOL)connected;
- (BOOL)isActive;
- (void)setIsActive:(BOOL)fp8;
- (void)setAccountLoginStatus:(int)fp8;
- (void)setAccountLoginStatus:(int)fp8 errorMessage:(id)fp12;
- (void)setAccountLoginStatus:(int)fp8 errorMessage:(id)fp12 reason:(unsigned int)fp16;
- (void)_syncWithRemoteBuddies;
- (void)groupsChanged:(id)fp8 error:(id)fp12;
- (int)compareNames:(id)fp8;
- (id)accountSubtypeInfo;
- (void)recalculateSubtypeInfo;
- (id)loginIMHandle;
- (id)arrayOfAllIMHandles;
- (Class)imHandleClass;
- (id)existingIMHandleWithID:(id)fp8 alreadyCanonical:(BOOL)fp12;
- (id)existingIMHandleWithID:(id)fp8;
- (id)imHandleWithID:(id)fp8 alreadyCanonical:(BOOL)fp12;
- (id)imHandleWithID:(id)fp8;
- (id)personForIMHandle:(id)fp8;
- (id)personSibsForIMHandle:(id)fp8;
- (unsigned int)sortOrderForIMHandle:(id)fp8 inGroup:(id)fp12;
- (void)setPresenceStatus:(BOOL)fp8 forIMHandle:(id)fp12 requestID:(id)fp16;
- (void)requestPresenceStatusFromIMHandle:(id)fp8;
- (id)imHandlesForIMPerson:(id)fp8;
- (BOOL)addIMHandle:(id)fp8 toIMPerson:(id)fp12;
- (BOOL)removeIMHandle:(id)fp8 fromIMPerson:(id)fp12;
- (void)_watchBuddiesIfNecessary;
- (void)watchBuddiesIfNecessary;
- (void)startWatchingIMHandle:(id)fp8;
- (void)stopWatchingIMHandle:(id)fp8;
- (void)forgetAllWatches;
- (void)_refreshLoginIMHandle;
- (id)imHandleForGuid:(id)fp8;
- (void)registerIMHandle:(id)fp8;
- (void)unregisterIMHandle:(id)fp8;
- (void)disconnectAllIMHandles;
- (id)buddyList;
- (void)imHandle:(id)fp8 buddyStatusChanged:(BOOL)fp12;
- (void)handleSubscriptionRequestFrom:(id)fp8;
- (BOOL)justLoggedIn;
- (void)nowLoggedIn;
- (void)nowLoggedOut;
- (void)forgetAllChats;
- (id)chatIDForRoomName:(id)fp8;
- (id)defaultChatSuffix;
- (struct _FZChatRoomValidity)validityOfChatRoomName:(id)fp8;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (void)removeObjectForKey:(id)fp8;
- (void)setDictionaryData:(id)fp8 forKey:(id)fp12;
- (id)dictionaryDataForKey:(id)fp8;
- (id)stringForKey:(id)fp8;
- (void)setString:(id)fp8 forKey:(id)fp12;
- (BOOL)boolForKey:(id)fp8;
- (void)setBool:(BOOL)fp8 forKey:(id)fp12;
- (int)integerForKey:(id)fp8;
- (void)setInteger:(int)fp8 forKey:(id)fp12;
- (void)systemNetworkDidChange;
- (void)systemDidWake;
- (void)systemWillSleep;
- (id)objectForPreferenceKey:(id)fp8;
- (void)setObject:(id)fp8 forPreferenceKey:(id)fp12;
- (void)removeObjectForPreferenceKey:(id)fp8;
- (void)setDictionaryData:(id)fp8 forPreferenceKey:(id)fp12;
- (id)dictionaryDataForPreferenceKey:(id)fp8;
- (id)stringForPreferenceKey:(id)fp8 defaultValue:(id)fp12;
- (void)setString:(id)fp8 forPreferenceKey:(id)fp12;
- (BOOL)boolForPreferenceKey:(id)fp8 defaultValue:(BOOL)fp12;
- (void)setBool:(BOOL)fp8 forPreferenceKey:(id)fp12;
- (int)integerForPreferenceKey:(id)fp8 defaultValue:(int)fp12;
- (void)setInteger:(int)fp8 forPreferenceKey:(id)fp12;

@end

@interface IMAccountController : NSObject
{
    NSMutableArray *_accounts;
    BOOL _isReadOnly;
}

+ (id)sharedInstance;
- (oneway void)release;
- (unsigned int)retainCount;
- (void)autoLogin;
- (id)init;
- (void)dealloc;
- (id)accountForUniqueID:(id)fp8;
- (id)accountAtIndex:(int)fp8;
- (int)numberOfAccounts;
- (int)numberOfAccountsForService:(id)fp8;
- (id)accountsForService:(id)fp8;
- (int)numberOfActiveAccountsForService:(id)fp8;
- (id)activeAccountsForService:(id)fp8;
- (int)numberOfConnectedAccountsForService:(id)fp8;
- (id)connectedAccountsForService:(id)fp8;
- (id)accountsWithCapability:(unsigned long long)fp8;
- (id)connectedAccountsWithCapability:(unsigned long long)fp8;
- (int)numberOfConnectedAccountsNotOfService:(id)fp8;
- (id)connectedAccountsNotOfService:(id)fp8;
- (BOOL)hasAccount:(id)fp8;
- (BOOL)canDeleteAccount:(id)fp8;
- (BOOL)accountActive:(id)fp8;
- (BOOL)readOnly;
- (void)setReadOnly:(BOOL)fp8;
- (void)_activeAccountChanged:(id)fp8;
- (BOOL)addAccount:(id)fp8;
- (BOOL)addAccount:(id)fp8 locally:(BOOL)fp12;
- (BOOL)addAccount:(id)fp8 atIndex:(int)fp12;
- (BOOL)addAccount:(id)fp8 atIndex:(int)fp12 locally:(BOOL)fp16;
- (BOOL)deleteAccount:(id)fp8;
- (BOOL)deleteAccount:(id)fp8 locally:(BOOL)fp12;
- (BOOL)deactivateAccount:(id)fp8;
- (BOOL)deactivateAccount:(id)fp8 withDisable:(BOOL)fp12;
- (BOOL)activateAccount:(id)fp8 locally:(BOOL)fp12;
- (BOOL)activateAccount:(id)fp8;
- (BOOL)activateAccount:(id)fp8 force:(BOOL)fp12;
- (BOOL)activateAccount:(id)fp8 force:(BOOL)fp12 locally:(BOOL)fp16;
- (BOOL)activateAndHandleReconnectAccount:(id)fp8;
- (BOOL)connectAccount:(id)fp8;
- (BOOL)disconnectAccount:(id)fp8;
- (BOOL)accountConnecting:(id)fp8;
- (BOOL)accountConnected:(id)fp8;
- (BOOL)canActivateAccount:(id)fp8;

@end

@interface IMAccountController (QuickAccountAccess)
- (id)anyAccountForService:(id)fp8 withLogin:(id)fp12;
- (id)anyActiveAccountForService:(id)fp8 withLogin:(id)fp12;
- (id)anyConnectedAccountForService:(id)fp8 withLogin:(id)fp12;
- (id)anyAccountForService:(id)fp8;
- (id)anyActiveAccountForService:(id)fp8;
- (id)anyConnectedAccountForService:(id)fp8;
@end

@interface IMAccountController (QuickAccountTypeAccess)
- (id)mostLoggedInAccount;
- (id)aimAccount;
- (id)jabberAccount;
- (id)allConnectedAccounts;
- (id)allActiveAccounts;
- (id)allAccounts;
@end

@interface IMAccountController (StatusAccess)
+ (id)bestAccountFromAccounts:(id)fp8;
- (id)bestAccountForStatus;
@end

@interface IMActionsController : NSObject
{
    NSMutableArray *_handlers;
}

+ (id)actionsController;
- (id)init;
- (void)dealloc;
- (void)addHandler:(id)fp8;
- (void)removeHandler:(id)fp8;
- (id)performActionsForEvent:(int)fp8 withIMHandle:(id)fp12;
- (id)performActionsForEvent:(int)fp8 withIMHandle:(id)fp12 withObject:(id)fp16;
- (id)performActionsForEvent:(int)fp8 withIMHandle:(id)fp12 withObject:(id)fp16 withChat:(id)fp20 silent:(BOOL)fp24;

@end

@interface IMPresence : DirectlyObservableObject <DirectlyObservableObjectObserver>
{
    BOOL _quiet;
    NSMutableArray *_imHandles;
    NSMutableSet *_imHandlesSet;
    unsigned int _previousStatus;
    unsigned int _status;
    NSString *_statusMessage;
    IMHandle *_mostAvailableIMHandle;
}

+ (id)notifications;
+ (id)selectors;
- (id)init;
- (void)dealloc;
- (BOOL)isQuiet;
- (void)setIsQuiet:(BOOL)fp8;
- (void)_observeIMHandle:(id)fp8;
- (void)_unobserveIMHandle:(id)fp8;
- (void)_imHandleCapabilitiesChanged:(id)fp8;
- (void)_imHandleStatusChanged:(id)fp8;
- (void)_imHandlePictureChanged:(id)fp8;
- (void)_imHandleInfoChanged:(id)fp8;
- (void)_imHandleGroupsChanged:(id)fp8;
- (void)_imHandleExtraPropsChanged:(id)fp8;
- (void)_imHandleMobileChanged:(id)fp8;
- (void)_imHandleCertsChanged:(id)fp8;
- (void)_imHandleSortOrderChanged:(id)fp8;
- (void)objectDidPostDirectNotification:(id)fp8;
- (void)_setMostAvailableIMHandle:(id)fp8;
- (BOOL)_fullRecache;
- (BOOL)canAddIMHandle:(id)fp8;
- (BOOL)addIMHandle:(id)fp8;
- (void)removeIMHandle:(id)fp8;
- (int)numberOfIMHandles;
- (BOOL)containsIMHandle:(id)fp8;
- (id)imHandleSet;
- (id)imHandles;
- (id)mostAvailableIMHandle;
- (id)groups;
- (id)firstName;
- (id)lastName;
- (id)fullName;
- (id)shortName;
- (id)displayName;
- (id)nameAndEmail;
- (unsigned int)status;
- (unsigned int)previousStatus;
- (id)statusMessage;
- (id)previousStatusMessage;
- (id)nameOfStatus;
- (BOOL)isMobile;
- (double)timeSinceWentOffline;
- (double)timeSinceStatusChanged;
- (void)postNotificationNamed:(id)fp8 forIMHandle:(id)fp12;
- (id)description;

@end

@interface IMBuddyListPresence : IMPresence
{
    NSSet *_filterGroups;
    IMPerson *_filterPerson;
    IMServiceImpl *_filterService;
    NSString *_filterSingleGroup;
}

- (id)initWithIMPersonFilter:(id)fp8 serviceFilter:(id)fp12 groupFilters:(id)fp16 quiet:(BOOL)fp20;
- (id)initWithIMPersonFilter:(id)fp8 serviceFilter:(id)fp12 groupFilters:(id)fp16;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)group;
- (id)service;
- (id)person;
- (id)_filterSingleGroup;
- (id)groups;
- (BOOL)canAddIMHandle:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)sortOrder;

@end

@interface IMDaemonController : NSObject <FZDaemon>
{
    IMRemoteObject<FZDaemon> *_remoteObject;
    IMLocalObject *_localObject;
    IMDaemonListener *_daemonListener;
    BOOL _hasCheckedForDaemon;
    BOOL _preventReconnect;
    BOOL _connectingToDaemon;
    unsigned int _gMyFZListenerCapabilities;
    NSMutableArray *_services;
    id _delegate;
}

+ (id)sharedController;
- (id)init;
- (void)dealloc;
- (void)_agentDidLaunchNotification:(id)fp8;
- (void)_handleDaemonException:(id)fp8;
- (void)_makeConnectionWithLaunch:(BOOL)fp8;
- (void)disconnectFromDaemonWithForce:(BOOL)fp8;
- (void)disconnectFromDaemon;
- (BOOL)_connectToDaemonWithLaunch:(BOOL)fp8;
- (BOOL)connectToDaemonWithLaunch:(BOOL)fp8;
- (BOOL)connectToDaemon;
- (void)sendABInformationToDaemon;
- (id)_remoteObject;
- (void)setMyPicture:(id)fp8 smallPictureData:(id)fp12;
- (void)setMyProfile:(id)fp8;
- (void)setMyStatus:(unsigned int)fp8 message:(id)fp12;
- (void)setMyStatus:(unsigned int)fp8 message:(id)fp12 forAccount:(id)fp16;
- (oneway void)_addressBookChanged:(id)fp8;
- (id)listener;
- (id)localPort;
- (BOOL)isConnecting;
- (BOOL)isConnected;
- (void)blockUntilConnected;
- (void)setCapabilities:(unsigned int)fp8;
- (unsigned int)capabilities;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_localObjectDiedNotification:(id)fp8;
- (void)_remoteObjectDiedNotification:(id)fp8;
- (void)localObjectDiedNotification:(id)fp8;
- (void)remoteObjectDiedNotification:(id)fp8;
- (oneway void)autoLoginActiveAccountsIfNecessary;
- (oneway void)loginAllAccounts;
- (oneway void)logoutAllAccounts;
- (oneway void)terminate;
- (oneway void)changeMyStatus:(id)fp8 forAccount:(id)fp12;
- (oneway void)setValue:(id)fp8 ofPersistentProperty:(id)fp12;
- (oneway void)setVCCapabilities:(unsigned long long)fp8;
- (oneway void)requestCurrentAVChatInfoForListenerID:(id)fp8 responseID:(id)fp12;
- (oneway void)requestAudioReflector:(BOOL)fp8 forListenerID:(id)fp12 responseID:(id)fp16;
- (oneway void)requestVideoStillForPerson:(id)fp8 forListenerID:(id)fp12 responseID:(id)fp16;
- (oneway void)provideCurrentAVChatInfo:(id)fp8 result:(unsigned int)fp12 transactionID:(unsigned int)fp16;
- (oneway void)provideVideoStill:(id)fp8 forPerson:(id)fp12 result:(unsigned int)fp16 transactionID:(unsigned int)fp20;
- (oneway void)setAVManagerClient:(id)fp8 URLToShare:(id)fp12;
- (oneway void)activateAccounts:(id)fp8;
- (oneway void)deactivateAccounts:(id)fp8;
- (oneway void)addAccount:(id)fp8 defaults:(id)fp12 service:(id)fp16;
- (oneway void)removeAccount:(id)fp8;
- (oneway void)writeAccount:(id)fp8 defaults:(id)fp12;
- (oneway void)holdBuddyUpdatesForAccount:(id)fp8;
- (oneway void)resumeBuddyUpdatesForAccount:(id)fp8;
- (void)_loginAccount:(id)fp8 autoLogin:(BOOL)fp12;
- (oneway void)autoLoginWithAccount:(id)fp8;
- (oneway void)loginWithAccount:(id)fp8;
- (oneway void)logoutOfAccount:(id)fp8;
- (oneway void)sessionCertificatesChangedForAccount:(id)fp8;
- (oneway void)enableSecureIM:(BOOL)fp8 forAccount:(id)fp12;
- (oneway void)disableCertificatesForPerson:(id)fp8 forAccount:(id)fp12;
- (oneway void)requestBuddyPicturesAndPropertiesForAccount:(id)fp8;
- (oneway void)requestProperty:(id)fp8 ofPerson:(id)fp12 forAccount:(id)fp16;
- (oneway void)setValue:(id)fp8 ofProperty:(id)fp12 ofPerson:(id)fp16 forAccount:(id)fp20;
- (oneway void)requestGroupsForAccount:(id)fp8;
- (oneway void)changeGroups:(id)fp8 forAccount:(id)fp12;
- (oneway void)changeGroup:(id)fp8 changes:(id)fp12 forAccount:(id)fp16;
- (oneway void)renameGroup:(id)fp8 to:(id)fp12 forAccount:(id)fp16;
- (oneway void)createChatForIMsWith:(id)fp8 isDirect:(BOOL)fp12 forAccount:(id)fp16;
- (oneway void)createChatWith:(id)fp8 invitation:(id)fp12 named:(id)fp16 forAccount:(id)fp20;
- (oneway void)goToChatNamed:(id)fp8 forAccount:(id)fp12;
- (oneway void)invitePerson:(id)fp8 toChat:(id)fp12 withMessage:(id)fp16;
- (oneway void)respond:(BOOL)fp8 toInvitationToChat:(id)fp12;
- (oneway void)sendMessage:(id)fp8 toChat:(id)fp12;
- (oneway void)leaveChat:(id)fp8;
- (oneway void)setPerson:(id)fp8 isIgnored:(BOOL)fp12 inChat:(id)fp16;
- (oneway void)sendStandaloneFileTransfer:(id)fp8;
- (oneway void)fileTransfer:(id)fp8 createdWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 acceptedWithPath:(id)fp12 autoRename:(BOOL)fp16 overwrite:(BOOL)fp20;
- (oneway void)fileTransferStopped:(id)fp8;
- (oneway void)fileTransferRemoved:(id)fp8;
- (oneway void)requestVCWithPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)cancelVCRequestWithPerson:(id)fp8 forAccount:(id)fp12;
- (oneway void)respondToVCInvitationWithPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendCounterProposalToPerson:(id)fp8 properties:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendVCUpdate:(id)fp8 toPerson:(id)fp12 forAccount:(id)fp16;
- (oneway void)sendAVMessageToPerson:(id)fp8 sessionID:(unsigned int)fp12 type:(unsigned int)fp16 userInfo:(id)fp20 forAccount:(id)fp24;
- (oneway void)setBlockList:(id)fp8 forAccount:(id)fp12;
- (oneway void)setAllowList:(id)fp8 forAccount:(id)fp12;
- (oneway void)setBlockingMode:(unsigned int)fp8 forAccount:(id)fp12;
- (oneway void)setBlockIdleStatus:(BOOL)fp8 forAccount:(id)fp12;
- (oneway void)acceptSubscriptionRequest:(BOOL)fp8 from:(id)fp12 forAccount:(id)fp16;
- (oneway void)requestSubscriptionTo:(id)fp8 forAccount:(id)fp12;
- (oneway void)startWatchingBuddy:(id)fp8 forAccount:(id)fp12;
- (oneway void)stopWatchingBuddy:(id)fp8 forAccount:(id)fp12;
- (oneway void)addListener:(id)fp8 withListenerID:(id)fp12 capabilities:(unsigned int)fp16;

@end

@interface IMDaemonListener : NSObject <FZDaemonListener>
{
    NSMutableDictionary *_persistentProperties;
    BOOL _setupComplete;
    BOOL _holdingChatMessages;
    NSMutableArray *_deferredChatMessages;
    NSMutableArray *_handlers;
    NSMutableDictionary *_services;
    NSDate *_myIdleSince;
    NSData *_myPicture;
    unsigned int _myStatus;
    NSString *_myStatusMessage;
    unsigned long long _vcCapabilities;
}

- (id)init;
- (void)dealloc;
- (BOOL)isSetupComplete;
- (void)addHandler:(id)fp8;
- (void)removeHandler:(id)fp8;
- (id)handlers;
- (id)allServices;
- (id)serviceWithName:(id)fp8;
- (void)_reallyProcessMyStatusChanged;
- (void)_processMyStatusChanged;
- (unsigned int)myStatus;
- (unsigned long)myIdleTime;
- (id)myStatusMessage;
- (unsigned long long)vcCapabilities;
- (void)_processDeferredInvitationDictionary:(id)fp8;
- (void)_deferNotification:(id)fp8;
- (BOOL)shouldHoldChatMessages;
- (BOOL)isHoldingChatMessages;
- (void)holdChatMessages;
- (void)releaseHeldChatMessages;
- (oneway void)defaultsChanged:(id)fp8 forService:(id)fp12;
- (oneway void)activeAccountsChanged:(id)fp8 forService:(id)fp12;
- (oneway void)account:(id)fp8 defaultsChanged:(id)fp12;
- (oneway void)accountAdded:(id)fp8 defaults:(id)fp12 service:(id)fp16;
- (oneway void)accountRemoved:(id)fp8;
- (oneway void)account:(id)fp8 loginStatusChanged:(unsigned int)fp12 message:(id)fp16 reason:(unsigned int)fp20 properties:(id)fp24;
- (oneway void)account:(id)fp8 statusChanged:(id)fp12;
- (oneway void)account:(id)fp8 capabilitiesChanged:(unsigned long long)fp12;
- (oneway void)vcCapabilitiesChanged:(unsigned long long)fp8;
- (oneway void)account:(id)fp8 buddyPropertiesChanged:(id)fp12;
- (oneway void)account:(id)fp8 buddyPictureChanged:(id)fp12 imageData:(id)fp16 imageHash:(id)fp20;
- (oneway void)account:(id)fp8 buddyProperties:(id)fp12 buddyPictures:(id)fp16;
- (oneway void)invitedToChat:(id)fp8 isChatRoom:(BOOL)fp12 invitation:(id)fp16;
- (oneway void)account:(id)fp8 directIMRequestFrom:(id)fp12 invitation:(id)fp16;
- (oneway void)chat:(id)fp8 statusChanged:(int)fp12;
- (oneway void)chat:(id)fp8 messageReceived:(id)fp12;
- (oneway void)chat:(id)fp8 showError:(id)fp12;
- (oneway void)chat:(id)fp8 member:(id)fp12 statusChanged:(int)fp16;
- (oneway void)standaloneFileTransferRegistered:(id)fp8;
- (oneway void)allFileTransfers:(id)fp8;
- (oneway void)fileTransfer:(id)fp8 createdWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithProperties:(id)fp12;
- (oneway void)fileTransfer:(id)fp8 updatedWithCurrentBytes:(unsigned long long)fp12 totalBytes:(unsigned long long)fp20 averageTransferRate:(unsigned long long)fp28;
- (oneway void)account:(id)fp8 invitedToVC:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 responseToVCRequest:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 cancelVCInviteFrom:(id)fp12;
- (oneway void)account:(id)fp8 counterProposalFrom:(id)fp12 properties:(id)fp16;
- (oneway void)account:(id)fp8 updateVCFrom:(id)fp12 data:(id)fp16;
- (oneway void)account:(id)fp8 handleAVMessage:(id)fp12 sessionID:(unsigned int)fp16 type:(unsigned int)fp20 userInfo:(id)fp24;
- (oneway void)currentAVChatInfoRequestedWithTransactionID:(unsigned int)fp8;
- (oneway void)audioReflectorRequested:(BOOL)fp8 transactionID:(unsigned int)fp12;
- (oneway void)videoStillForPersonRequested:(id)fp8 withTransactionID:(unsigned int)fp12;
- (oneway void)currentAVChatInfoProvided:(id)fp8 result:(unsigned int)fp12 responseID:(id)fp16;
- (oneway void)videoStill:(id)fp8 providedForPerson:(id)fp12 result:(unsigned int)fp16 responseID:(id)fp20;
- (oneway void)setAVManagerRequested:(BOOL)fp8 URLToShare:(id)fp12;
- (oneway void)account:(id)fp8 groupsChanged:(id)fp12 error:(id)fp16;
- (oneway void)account:(id)fp8 handleSubscriptionRequestFrom:(id)fp12;
- (oneway void)account:(id)fp8 blockListChanged:(id)fp12;
- (oneway void)account:(id)fp8 allowListChanged:(id)fp12;
- (oneway void)account:(id)fp8 blockingModeChanged:(unsigned int)fp12;
- (oneway void)account:(id)fp8 blockIdleStatusChanged:(BOOL)fp12;
- (oneway void)showInvalidCertNotificationForAccount:(id)fp8;
- (oneway void)showForgotPasswordNotificationForAccount:(id)fp8;
- (oneway void)account:(id)fp8 postedError:(id)fp12;
- (id)persistentProperties;
- (id)valueOfPersistentProperty:(id)fp8;
- (void)_cacheValue:(id)fp8 forPersistentProperty:(id)fp12;
- (oneway void)daemonPersistentProperty:(id)fp8 changedTo:(id)fp12;
- (oneway void)account:(id)fp8 status:(id)fp12 capabilities:(unsigned long long)fp16 serviceLoginStatus:(unsigned int)fp24 loginStatusMessage:(id)fp28;
- (oneway void)services:(id)fp8 persistentProperties:(id)fp12;
- (oneway void)service:(id)fp8 properties:(id)fp12 defaults:(id)fp16 defaultAccountSettings:(id)fp20 allAccounts:(id)fp24 activeAccounts:(id)fp28;
- (oneway void)setupComplete;

@end

@interface IMFileTransferCenter : NSObject
{
    NSMutableDictionary *_guidToTransferMap;
    NSMutableDictionary *_guidToRemovedTransferMap;
    NSMutableDictionary *_accountIDToTransferGUIDsMap;
    NSMutableArray *_preauthorizedInfos;
    NSMutableArray *_preauthorizedGUIDs;
    NSMutableSet *_activeTransfers;
    NSMutableSet *_pendingTransfers;
}

+ (id)sharedInstance;
+ (void)setTransferCenterClass:(Class)fp8;
+ (Class)transferCenterClass;
+ (Class)fileTransferClass;
- (id)init;
- (void)dealloc;
- (BOOL)hasPendingFileTransfers;
- (void)_addPendingTransfer:(id)fp8;
- (void)_removePendingTransfer:(id)fp8;
- (void)acknowledgePendingTransfer:(id)fp8;
- (void)acknowledgeAllPendingTransfers;
- (BOOL)hasActiveFileTransfers;
- (void)_addActiveTransfer:(id)fp8;
- (void)_removeActiveTransfer:(id)fp8;
- (void)_removeAllActiveTransfers;
- (void)_clearTransfers;
- (void)_addTransfer:(id)fp8 toAccount:(id)fp12;
- (void)_addTransfer:(id)fp8;
- (id)guidForNewOutgoingTransferWithLocalURL:(id)fp8;
- (void)assignTransfer:(id)fp8 toAccount:(id)fp12 otherPerson:(id)fp16 securityLevel:(int)fp20;
- (id)transferForGUID:(id)fp8;
- (id)transferForGUID:(id)fp8 includeRemoved:(BOOL)fp12;
- (void)sendTransfer:(id)fp8;
- (void)acceptTransfer:(id)fp8 withPath:(id)fp12 autoRename:(BOOL)fp16 overwrite:(BOOL)fp20;
- (void)stopTransfer:(id)fp8;
- (void)removeTransfer:(id)fp8;
- (void)retargetTransfer:(id)fp8 toPath:(id)fp12;
- (id)transfersForAccount:(id)fp8;
- (id)activeTransfers;
- (id)orderedTransfers;
- (BOOL)isFileTransfer:(id)fp8 preauthorizedWithDictionary:(id)fp12;
- (void)preauthorizeFileTransferFromOtherPerson:(id)fp8 account:(id)fp12 filename:(id)fp16 saveToPath:(id)fp20;
- (BOOL)wasFileTransferPreauthorized:(id)fp8;
- (void)acceptFileTransferIfPreauthorzed:(id)fp8;
- (void)_handleStandaloneFileTransferRegistered:(id)fp8;
- (void)_handleAllFileTransfers:(id)fp8;
- (void)_handleFileTransfer:(id)fp8 createdWithProperties:(id)fp12;
- (void)_handleFileTransfer:(id)fp8 updatedWithProperties:(id)fp12;
- (void)_handleFileTransfer:(id)fp8 updatedWithCurrentBytes:(unsigned long long)fp12 totalBytes:(unsigned long long)fp20 averageTransferRate:(unsigned long long)fp28;

@end

@interface IMHandle : DirectlyObservableObject <NSCoding>
{
    BOOL _beingTornDown;
    NSString *_guid;
    IMAccount *_account;
    NSString *_id;
    unsigned int _locationIndex;
    NSDictionary *_otherServiceIDs;
    unsigned long long _capabilities;
    BOOL _isBuddy;
    NSDate *_idleSince;
    BOOL _willUpdateIdleTime;
    NSDate *_feedUpdatedDate;
    NSDictionary *_extraProps;
    NSDictionary *_certs;
    NSSet *_groups;
    int _priority;
    unsigned int _subscriptionStatus;
    IMPerson *_person;
    NSString *_abFirstName;
    NSString *_abLastName;
    NSString *_abFullName;
    NSString *_abNickname;
    NSArray *_abEmails;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_fullName;
    NSString *_nickname;
    NSArray *_emails;
    NSString *_canonicalFormOfID;
    NSString *_IDWithoutLocation;
    NSString *_IDWithTrimmedServer;
    NSString *_uniqueName;
    BOOL _isMobile;
    BOOL _isBot;
    int _isAnonymous;
    NSData *_pictureData;
    unsigned int _status;
    NSString *_statusMsg;
    NSString *_processedStatusMsg;
    NSAttributedString *_richStatusMsg;
    NSDate *_whenWentOffline;
    NSDate *_whenStatusChanged;
    unsigned int _prevStatus;
    NSString *_prevStatusMsg;
    NSMutableArray *_notificationNameQueue;
    BOOL _blockNotifications;
    BOOL _hasTemporaryWatch;
    NSURL *_statusMessageURL;
    NSURL *_statusURL;
    unsigned int _sortOrder;
    unsigned int _customPictureChecked:1;
    int _notificationQueueCount;
}

+ (void)setNotificationsEnabled:(BOOL)fp8;
+ (BOOL)notificationsEnabled;
+ (void)_loadStatusNames;
+ (id)nameOfStatus:(unsigned int)fp8;
+ (id)imHandlesForIMPerson:(id)fp8;
+ (id)bestIMHandleInArray:(id)fp8;
+ (id)filterIMHandlesForAccountSiblings:(id)fp8 onAccount:(id)fp12;
+ (id)filterIMHandlesForBestAccountSiblings:(id)fp8;
- (id)init;
- (id)initWithAccount:(id)fp8 ID:(id)fp12;
- (oneway void)release;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)canBeRemovedFromBuddyList;
- (id)imHandleForOtherAccount:(id)fp8;
- (id)groupsArray;
- (id)groups;
- (void)setAnonymous:(BOOL)fp8;
- (BOOL)isAnonymous;
- (void)_postNotificationName:(id)fp8 userInfo:(id)fp12;
- (void)postNotificationName:(id)fp8;
- (id)ID;
- (id)uniqueName;
- (void)setUniqueName:(id)fp8;
- (id)nameAndEmail;
- (id)account;
- (id)service;
- (unsigned int)hash;
- (id)guid;
- (void)clearABPerson;
- (BOOL)resetABPerson;
- (id)_abPersonCreateIfNeeded;
- (id)person;
- (BOOL)areABPropertiesRecent;
- (void)resetABProperties;
- (void)setIMPerson:(id)fp8;
- (id)_IDWithTrimmedServer;
- (BOOL)_hasServiceNameProperties;
- (BOOL)_hasABName;
- (id)_nameUsingUnique:(BOOL)fp8;
- (id)name;
- (id)fullName;
- (id)nameAndID;
- (void)resetUniqueName;
- (BOOL)hasName;
- (id)nickname;
- (id)firstName;
- (id)lastName;
- (void)_setABPersonFirstName:(id)fp8 lastName:(id)fp12;
- (void)_setBaseFirstName:(id)fp8 lastName:(id)fp12;
- (void)setImageData:(id)fp8 andUpdateABPerson:(BOOL)fp12;
- (void)setNickname:(id)fp8 andUpdateABPerson:(BOOL)fp12;
- (void)setFirstName:(id)fp8 lastName:(id)fp12 andUpdateABPerson:(BOOL)fp16;
- (void)setEmail:(id)fp8 andUpdateABPerson:(BOOL)fp12;
- (id)email;
- (void)setEmails:(id)fp8 andUpdateABPerson:(BOOL)fp12;
- (id)emails;
- (BOOL)canBeAddedToBuddyList;
- (BOOL)canBeSecure;
- (BOOL)isSystemUser;
- (void)setIsMobile:(BOOL)fp8;
- (BOOL)isMobile;
- (void)setIsBot:(BOOL)fp8;
- (BOOL)isBot;
- (id)mobileDeviceName;
- (BOOL)hasServer;
- (BOOL)hasLocation;
- (id)server;
- (void)setPriority:(int)fp8;
- (int)priority;
- (void)setOtherServiceIDs:(id)fp8;
- (id)otherServiceIDs;
- (BOOL)isBuddy;
- (BOOL)isLoginIMHandleForAnyAccount;
- (BOOL)isLoginIMHandle;
- (id)extraProperties;
- (void)requestValueOfProperty:(id)fp8;
- (void)setValue:(id)fp8 ofExtraProperty:(id)fp12;
- (BOOL)watchingIMHandle;
- (void)setHasTemporaryWatch:(BOOL)fp8;
- (BOOL)isBetterThanIMHandle:(id)fp8;
- (id)bestIMHandleForService:(id)fp8;
- (id)bestIMHandleForAccount:(id)fp8;
- (id)bestAccountSibling;
- (id)bestIMHandleForAccount:(id)fp8 onService:(id)fp12 inGroup:(id)fp16 otherThan:(id)fp20;
- (id)bestSiblingInGroup:(id)fp8 otherThan:(id)fp12;
- (id)bestSiblingInGroup:(id)fp8;
- (id)bestSibling;
- (void)_setExtraProperties:(id)fp8;
- (void)propertiesChanged:(id)fp8;
- (BOOL)_isMyIDInList:(id)fp8;
- (BOOL)isVisiblyBlocked;
- (BOOL)isBlocked;
- (void)setBlocked:(BOOL)fp8;
- (unsigned int)sortOrderInGroup:(id)fp8;
- (id)accountTypeName;
- (id)statusURL;
- (id)location;
- (id)IDWithoutLocation;
- (id)imHandleWithoutLocation;
- (id)existingIMHandleWithoutLocation;
- (id)dependentIMHandles;
- (BOOL)isDependentOnIMHandle:(id)fp8;
- (unsigned int)subscriptionStatus;
- (void)_updateStatusBasedOnSubscription;
- (void)setSubscriptionStatus:(unsigned int)fp8;
- (unsigned int)status;
- (unsigned int)previousStatus;
- (void)setPersonStatus:(unsigned int)fp8;
- (void)statusChanged:(unsigned int)fp8 message:(id)fp12;
- (void)statusMessageChanged:(id)fp8;
- (void)statusChanged:(unsigned int)fp8;
- (id)nameOfStatus;
- (double)idleTime;
- (void)setIdleSince:(id)fp8;
- (id)feedUpdatedDate;
- (void)setFeedUpdatedDate:(id)fp8;
- (void)setStatusURLFromString:(id)fp8;
- (id)offlineString;
- (id)idleString;
- (void)_filterStatusMessage;
- (id)statusMessage;
- (id)previousStatusMessage;
- (id)richStatusMessage;
- (void)_clearStatusMessageURLCache;
- (void)_scheduleIdleTimeUpdate;
- (void)_updateIdleTime;
- (void)_updateIdleTimer;
- (void)setStatus:(unsigned int)fp8 message:(id)fp12 richMessage:(id)fp16;
- (double)timeSinceWentOffline;
- (double)timeSinceStatusChanged;
- (id)_nameForComparisonPreferFirst:(BOOL)fp8;
- (int)compareFirstNames:(id)fp8;
- (int)compareLastNames:(id)fp8;
- (int)compareStatus:(id)fp8;
- (int)compareIDs:(id)fp8;
- (int)compareAccountNames:(id)fp8;
- (BOOL)matchesIMHandle:(id)fp8;
- (BOOL)hasOtherSiblings;
- (id)imHandles;
- (id)existingAccountSiblingsArray;
- (id)accountSiblingsArray;
- (id)siblings;
- (BOOL)isAccountSiblingOf:(id)fp8;
- (BOOL)isSiblingOf:(id)fp8;
- (unsigned long long)capabilities;
- (void)setCapabilities:(unsigned long long)fp8;
- (BOOL)hasCapability:(unsigned long long)fp8;
- (id)customPictureData;
- (void)setCustomPictureData:(id)fp8;
- (void)setCustomPictureData:(id)fp8 key:(id)fp12;
- (id)description;

@end

@interface IMHandle (AddressBook)
- (void)saveChanges;
- (void)addToAddressBook;
- (void)removeFromAddressBook;
- (void)sendNotificationABPersonChanged;
@end

@interface IMHandle (IMHandleRegistrarAdditions)
- (id)imHandleRegistrarGUID;
@end

@interface IMHandle (NotificationBlocking)
- (void)stopPostingNotifications;
- (void)startPostingNotifications;
@end

@interface IMHandle (PublicAPIMethods)
- (id)publicAPIPropertiesDictionary;
@end

@interface IMHandle (QueueNotifications)
- (BOOL)shouldQueueNotifications;
- (void)beginNotificationQueue;
- (void)releaseNotificationQueue;
@end

@interface IMHandleRegistrar : NSObject
{
    NSDate *_ABLoadDate;
    int _nameStyle;
    NSMutableDictionary *_siblingsMap;
    NSMutableArray *_allIMHandles;
    NSMutableDictionary *_guidToIMHandleMap;
    NSMutableDictionary *_candidateNamesMap;
    NSMutableDictionary *_usedUniqueNames;
    NSMutableSet *_knownConflictingNames;
}

+ (id)sharedInstance;
- (void)_noteABLoadTimeUpdated;
- (void)addressBookChanged:(id)fp8;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)init;
- (void)dealloc;
- (id)imHandleForGUID:(id)fp8;
- (int)nameStyle;
- (void)setNameStyle:(int)fp8;
- (void)_emptySiblingCacheForIMHandleGUID:(id)fp8;
- (void)_buildSiblingsForIMHandle:(id)fp8;
- (void)_clearSiblingsCacheForIMHandle:(id)fp8 rebuildAfter:(BOOL)fp12;
- (void)registerIMHandle:(id)fp8;
- (void)clearNameReservationsForObject:(id)fp8;
- (void)unregisterIMHandle:(id)fp8;
- (void)clearSiblingCacheForIMHandle:(id)fp8;
- (id)siblingsForIMHandle:(id)fp8;
- (id)allIMHandles;
- (id)candidateUniqueNamesForIMHandle:(id)fp8;
- (void)reassessIMHandleForUniqueName:(id)fp8 rebuild:(BOOL)fp12;
- (void)reassessIMHandleForUniqueName:(id)fp8;
- (void)_rebuildUniqueNameMapWithStyleChange:(BOOL)fp8;
- (void)rebuildUniqueNameMap;
- (void)imHandleInfoChanged:(id)fp8;

@end

@interface IMMe : NSObject
{
    IMPerson *_person;
    int _pictureLoadTag;
    NSString *_abNickname;
    NSString *_abFirstName;
    NSString *_abFullName;
    NSString *_abLastName;
    NSArray *_abEmails;
    NSMutableArray *_imHandles;
    NSMutableArray *_allLoginIMHandles;
    NSMutableArray *_meLoginIMHandles;
}

+ (id)fallbackUserName;
+ (id)me;
+ (id)imHandleForService:(id)fp8;
- (id)init;
- (id)guid;
- (void)dealloc;
- (id)_imHandlesWithIDs:(id)fp8 onAccount:(id)fp12;
- (void)rebuildIMHandles;
- (void)resetABPerson;
- (void)setIMPerson:(id)fp8;
- (id)person;
- (BOOL)addLoginIMHandle:(id)fp8;
- (BOOL)removeLoginIMHandle:(id)fp8;
- (id)loginIMHandles;
- (BOOL)addIMHandle:(id)fp8;
- (BOOL)isIMHandleLoginIMHandle:(id)fp8;
- (BOOL)removeIMHandle:(id)fp8;
- (void)setFirstName:(id)fp8 lastName:(id)fp12;
- (id)nickname;
- (id)firstName;
- (id)emails;
- (id)email;
- (id)lastName;
- (id)fullName;
- (id)bestIMHandle;
- (id)imHandles;
- (void)myPictureChanged;

@end

@interface IMParentalControls : NSObject
{
    BOOL _active;
    BOOL _disableAV;
    BOOL _disableAimService;
    BOOL _forceAimWhitelist;
    NSMutableSet *_aimWhitelist;
    BOOL _disableSubnetService;
    BOOL _forceSubnetWhitelist;
    NSMutableSet *_subnetWhitelist;
    BOOL _disableJabberService;
    BOOL _forceJabberWhitelist;
    NSMutableSet *_jabberWhitelist;
    BOOL _forceChatLogging;
    BOOL _shouldPostNotifications;
}

+ (id)objectForKey:(id)fp8;
+ (id)standardControls;
- (void)_updateParentalSettings;
- (id)init;
- (void)_managedPrefsNotification:(id)fp8;
- (BOOL)okToConnectAccount:(id)fp8;
- (BOOL)accountIsEnabled:(id)fp8;
- (BOOL)accountHasWhitelist:(id)fp8;
- (BOOL)active;
- (BOOL)disableAV;
- (BOOL)forceChatLogging;
- (BOOL)disableAimService;
- (BOOL)forceAimWhitelist;
- (id)aimWhitelist;
- (BOOL)disableSubnetService;
- (BOOL)forceSubnetWhitelist;
- (id)subnetWhitelist;
- (BOOL)disableJabberService;
- (BOOL)forceJabberWhitelist;
- (id)jabberWhitelist;
- (void)setShouldPostNotifications:(BOOL)fp8;

@end

@interface IMPeople : NSObject
{
    NSMutableArray *_people;
    BOOL _dirty;
    int _coalesceCount;
    BOOL _hidePeople;
}

- (id)init;
- (void)dealloc;
- (BOOL)dirty;
- (void)setDirty:(BOOL)fp8;
- (BOOL)hidePeople;
- (void)setShouldHidePeople:(BOOL)fp8;
- (void)saveChanges;
- (void)removeNotificationObserver:(id)fp8;
- (void)addNotificationObserver:(id)fp8 selector:(SEL)fp12;
- (unsigned int)count;
- (BOOL)containsIMHandle:(id)fp8;
- (id)groups;
- (id)people;
- (void)_countChanged;
- (void)postNotificationNamed:(id)fp8 imHandle:(id)fp12;
- (void)addedIMHandle:(id)fp8;
- (void)_addedPeople:(id)fp8;
- (void)removedIMHandle:(id)fp8;
- (void)beginCoalescedChanges;
- (void)endCoalescedChanges;
- (BOOL)coalescingChanges;
- (BOOL)addIMHandle:(id)fp8;
- (BOOL)removeIMHandle:(id)fp8;
- (BOOL)removePeopleFromArray:(id)fp8;
- (BOOL)addPeopleFromArray:(id)fp8 skipMe:(BOOL)fp12;
- (BOOL)addPeopleFromArray:(id)fp8;

@end

@interface IMPeople (BuddyListPeople)
- (void)imHandle:(id)fp8 buddyStatusChanged:(BOOL)fp12;
@end

@interface IMPeopleCollection : IMPeople
{
    NSMutableArray *_collectedPeople;
}

- (id)init;
- (void)dealloc;
- (void)addPeople:(id)fp8;
- (void)_collectionNotification:(id)fp8;
- (void)removePeople:(id)fp8;
- (id)people;
- (id)groups;
- (BOOL)containsPerson:(id)fp8;

@end

@interface IMPerson : NSObject
{
    ABPerson *_abPerson;
}

+ (id)personWithABPerson:(id)fp8;
+ (id)_initialABPropertyLabelForProperty:(id)fp8;
- (id)init;
- (id)initWithABPerson:(id)fp8;
- (id)abPerson;
- (void)dealloc;
- (BOOL)isCompany;
- (id)companyName;
- (void)setNickname:(id)fp8;
- (id)nickname;
- (id)fullName;
- (id)firstName;
- (void)setFirstName:(id)fp8;
- (id)lastName;
- (void)setLastName:(id)fp8;
- (void)setFirstName:(id)fp8 lastName:(id)fp12;
- (id)emailHandlesForService:(id)fp8 includeBaseEmail:(BOOL)fp12;
- (id)emailHandlesForService:(id)fp8;
- (id)emails;
- (id)allEmails;
- (void)setEmails:(id)fp8;
- (BOOL)isInAddressBook;
- (id)valuesForProperty:(id)fp8;
- (void)setValues:(id)fp8 forProperty:(id)fp12;
- (id)allHandlesForProperty:(id)fp8;
- (id)mobileNumbers;
- (void)save;
- (void)appendID:(id)fp8 toProperty:(id)fp12;
- (BOOL)containsHandle:(id)fp8 forServiceProperty:(id)fp12;
- (id)uniqueID;
- (BOOL)isEqualToIMPerson:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)setImageData:(id)fp8;
- (id)imageData;
- (unsigned int)hash;

@end

@interface IMPerson (IMHandleRegistrarAdditions)
- (id)imHandleRegistrarGUID;
@end

@interface IMPerson (LookupAdditions)
+ (id)allPeople;
+ (id)existingABPersonWithFirstName:(id)fp8 lastName:(id)fp12;
+ (id)existingABPersonWithFirstName:(id)fp8 andLastName:(id)fp12 orEmail:(id)fp16;
+ (id)existingABPersonForPerson:(id)fp8;
@end

/*@interface IMService : NSObject
{
}

+ (void)forgetStatusImageAppearance;
+ (id)imageNameForStatus:(unsigned int)fp8;
+ (id)imageURLForStatus:(unsigned int)fp8;
+ (id)allServices;
+ (id)allServicesNonBlocking;
+ (id)serviceWithNameNonBlocking:(id)fp8;
+ (id)serviceWithName:(id)fp8;
+ (id)notificationCenter;
+ (unsigned int)myStatus;
+ (id)myIdleTime;
+ (BOOL)isEmailAddress:(id)fp8 inDomains:(id)fp12;
+ (unsigned int)statusForIMPerson:(id)fp8;
+ (unsigned int)statusForABPerson:(id)fp8;
+ (id)canonicalFormOfID:(id)fp8 withIDSensitivity:(int)fp12;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEnabled;
- (void)login;
- (void)logout;
- (id)localizedName;
- (id)localizedShortName;
- (id)name;
- (unsigned int)status;
- (id)infoForScreenName:(id)fp8;
- (id)infoForAllScreenNames;
- (id)infoForPreferredScreenNames;
- (id)canonicalFormOfID:(id)fp8;
- (id)peopleWithScreenName:(id)fp8;
- (id)screenNamesForPerson:(id)fp8;

@end*/

@interface IMService (Deprecated)
- (id)infoForPerson:(id)fp8;
- (id)infoForAllPeople;
- (id)infoForDisplayedPeople;
@end

@interface IMService (IMService_GetService)
+ (id)aimService;
+ (id)subnetService;
+ (id)jabberService;
@end

@interface IMServiceAgent : NSObject
{
    NSDictionary *_currentAVChatInfo;
}

+ (oneway void)setServiceAgentCapabilities:(int)fp8;
+ (int)serviceAgentCapabilities;
+ (id)sharedAgent;
+ (id)imageURLForStatus:(unsigned int)fp8;
+ (id)imageNameForStatus:(unsigned int)fp8;
+ (oneway void)forgetStatusImageAppearance;
+ (id)notificationCenter;
- (id)serviceWithName:(id)fp8;
- (id)serviceWithNameNonBlocking:(id)fp8;
- (id)notificationCenter;
- (oneway void)setMyStatus:(unsigned int)fp8 message:(id)fp12;
- (id)myAvailableMessages;
- (id)myAwayMessages;
- (id)currentAVChatInfo;
- (unsigned int)requestAudioReflectorStart;
- (unsigned int)requestAudioReflectorStop;
- (unsigned int)requestVideoStillForPerson:(id)fp8;
- (unsigned long long)vcCapabilities;
- (id)myPictureData;
- (void)dealloc;

@end

@interface IMServiceAgentCenter : NSNotificationCenter
{
    id _delegate;
}

- (void)dealloc;
- (void)finalize;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (oneway void)addObserver:(id)fp8 selector:(SEL)fp12 name:(id)fp16 object:(id)fp20;
- (oneway void)removeObserver:(id)fp8 name:(id)fp12 object:(id)fp16;
- (void)_postUnpackedNotification:(id)fp8;
- (void)_postNotificationOnMainThread:(id)fp8;
- (oneway void)postNotification:(id)fp8;
- (oneway void)postNotificationName:(id)fp8 object:(id)fp12;
- (oneway void)postNotificationName:(id)fp8 object:(id)fp12 userInfo:(id)fp16;

@end

@interface IMServiceAgentImpl : IMServiceAgent
{
    IMServiceAgentCenter *_notifCenter;
    BOOL _anyAccountsConnected;
}

+ (id)sharedAgent;
+ (void)initialize;
+ (id)notificationCenter;
+ (void)forgetStatusImageAppearance;
+ (void)_statusImageAppearanceChanged:(id)fp8;
+ (void)_determineStatusImageAppearance;
+ (id)imageNameForStatus:(unsigned int)fp8;
+ (id)imageURLForStatus:(unsigned int)fp8;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (void)daemonConnectionLost;
- (oneway void)launchIfNecessary;
- (id)serviceWithNameNonBlocking:(id)fp8;
- (id)serviceWithName:(id)fp8;
- (oneway void)centerWillAddObserver;
- (oneway void)centerDidRemoveObserver;
- (id)notificationCenter;
- (void)_statusImageAppearanceChanged:(id)fp8;
- (void)setMyStatus:(unsigned int)fp8 message:(id)fp12;
- (void)_customMessagesChanged:(id)fp8;
- (id)myAvailableMessages;
- (id)myAwayMessages;
- (void)imHandleStatusChangedNotification:(id)fp8;
- (void)imHandleInfoChangedNotification:(id)fp8;
- (void)_processAccountStatusChange;
- (oneway void)account:(id)fp8 loginStatusChanged:(unsigned int)fp12 message:(id)fp16 reason:(unsigned int)fp20 properties:(id)fp24;
- (oneway void)activeAccountsChanged:(id)fp8 forService:(id)fp12;
- (oneway void)services:(id)fp8 myStatus:(id)fp12 persistentProperties:(id)fp16;
- (oneway void)setupComplete;
- (oneway void)vcCapabilitiesChanged:(unsigned long long)fp8;
- (unsigned long long)vcCapabilities;

@end

@interface IMServiceImpl : IMService
{
    NSString *_name;
    NSString *_localizedName;
    NSString *_localizedShortName;
    NSMutableDictionary *_cardMap;
    NSDictionary *_personToIDMap;
    IMAccount *_bestAccount;
    NSDictionary *_serviceDefaults;
    NSDictionary *_serviceProps;
    NSDictionary *_defaultSettings;
    unsigned int _screenNameSensitivity;
    BOOL _handlesChatInvites;
    BOOL _supportsSMS;
    NSString *_abProperty;
    NSArray *_emailDomains;
    NSImage *_icon;
    BOOL _iconChecked;
}

+ (Class)serviceClass;
+ (void)setServiceClass:(Class)fp8;
+ (id)serviceWithInternalName:(id)fp8;
+ (id)supportedCountryCodes;
+ (BOOL)systemSupportsSMSSending;
- (id)initWithName:(id)fp8;
- (void)dealloc;
- (void)_syncWithRemoteBuddies;
- (void)_calculateBestAccount;
- (void)accountInitialSyncPerformed:(id)fp8;
- (BOOL)initialSyncPerformed;
- (void)doneSetup;
- (void)disconnect;
- (void)statusChangedForAccount:(id)fp8 from:(unsigned int)fp12 to:(unsigned int)fp16;
- (BOOL)equalID:(id)fp8 andID:(id)fp12;
- (id)canonicalFormOfID:(id)fp8;
- (int)compareNames:(id)fp8;
- (void)_blockUntilInitialSyncPerformed;
- (unsigned int)status;
- (id)infoForScreenName:(id)fp8;
- (id)infoForAllScreenNames;
- (id)infoForPreferredScreenNames;
- (id)myScreenNames;
- (id)serviceProperties;
- (void)setServiceProperties:(id)fp8;
- (void)setServiceDefaults:(id)fp8;
- (id)serviceDefaults;
- (id)defaultAccountSettings;
- (void)setDefaultAccountSettings:(id)fp8;
- (BOOL)supportsAdding;
- (BOOL)isPersistent;
- (BOOL)isEnabled;
- (BOOL)handlesChatInvites;
- (id)localizedName;
- (id)localizedShortName;
- (unsigned int)emailDomainOfID:(id)fp8;
- (unsigned int)IDSensitivity;
- (id)addressBookProperty;
- (id)emailDomains;
- (id)name;
- (id)shortName;
- (BOOL)allowsMultipleConnections;
- (int)buddyNotesMaxByteLength;
- (id)internalName;
- (id)accountIDs;
- (id)description;
- (id)_IDsToMapForIMPerson:(id)fp8;
- (void)_addAddressBookCards:(id)fp8 toMap:(id)fp12;
- (void)_dumpCardMap;
- (id)newIDToCardMap;
- (void)updateIDToCardMapWithNotification:(id)fp8;
- (void)clearIDToCardMap;
- (id)cardMap;
- (id)imABPeopleWithScreenName:(id)fp8;
- (id)peopleWithScreenName:(id)fp8;
- (id)_personToIDMap;
- (id)screenNamesForIMPerson:(id)fp8;
- (id)screenNamesForPerson:(id)fp8;
- (void)defaultsChanged:(id)fp8;
- (void)activeAccountsChanged:(id)fp8;
- (Class)accountClass;

@end

@interface NSSet (FastIMHandleCompareAdditions)
- (BOOL)fastIsEqualToPointerCompareSet:(id)fp8;
@end

